#!/usr/bin/env bash
#
# gen-secrets.sh
#
# Generates the git-ignored local build secrets from the project-root .env,
# so a local build matches what CI assembles from repository secrets. Run this
# once after editing .env (and before `flutter build`). It NEVER prints secret
# values — only confirmation + lengths.
#
# Produces:
#   lib/config/secrets.dart                 (Telegram apiId / apiHash)
#   android/app/upload-keystore.jks         (decoded from ANDROID_KEYSTORE_BASE64)
#   android/key.properties                  (release signing config)
#
# .env keys (see also .github/workflows/release.yml):
#   TELEGRAM_API_ID, TELEGRAM_API_HASH                         — required
#   ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD,
#   ANDROID_KEY_ALIAS  [, ANDROID_KEY_PASSWORD]                — optional (signing)
# If the ANDROID_* keys are absent, signing is skipped and release builds
# fall back to the debug key.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found in $REPO_ROOT (copy your secrets there)." >&2
  exit 1
fi

# Load .env without leaking it into the shell's command echo.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# ---- 1. Telegram credentials → lib/config/secrets.dart -----------------------
: "${TELEGRAM_API_ID:?missing TELEGRAM_API_ID in .env}"
: "${TELEGRAM_API_HASH:?missing TELEGRAM_API_HASH in .env}"
if ! [[ "$TELEGRAM_API_ID" =~ ^[0-9]+$ ]]; then
  echo "ERROR: TELEGRAM_API_ID must be an integer." >&2
  exit 1
fi

mkdir -p lib/config
cat > lib/config/secrets.dart <<EOF
//
//  secrets.dart — git-ignored. Generated by scripts/gen-secrets.sh from .env.
//  Do not edit by hand; re-run the script instead.
//
class Secrets {
  static const int apiId = ${TELEGRAM_API_ID};
  static const String apiHash = '${TELEGRAM_API_HASH}';
  static bool get isConfigured => apiId != 0 && apiHash.isNotEmpty;
}
EOF
echo "✓ lib/config/secrets.dart  (api_id len=${#TELEGRAM_API_ID}, api_hash len=${#TELEGRAM_API_HASH})"

# ---- 2. Signing → android/app/upload-keystore.jks + android/key.properties ---
if [[ -n "${ANDROID_KEYSTORE_BASE64:-}" ]]; then
  : "${ANDROID_KEYSTORE_PASSWORD:?missing ANDROID_KEYSTORE_PASSWORD in .env}"
  : "${ANDROID_KEY_ALIAS:?missing ANDROID_KEY_ALIAS in .env}"
  # Most upload keys use one password for the store and the key; fall back to it
  # when ANDROID_KEY_PASSWORD is not set separately.
  KEYPASS="${ANDROID_KEY_PASSWORD:-$ANDROID_KEYSTORE_PASSWORD}"

  echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
  cat > android/key.properties <<EOF
storePassword=${ANDROID_KEYSTORE_PASSWORD}
keyPassword=${KEYPASS}
keyAlias=${ANDROID_KEY_ALIAS}
storeFile=upload-keystore.jks
EOF
  echo "✓ android/app/upload-keystore.jks + android/key.properties  (alias=${ANDROID_KEY_ALIAS}, $(wc -c < android/app/upload-keystore.jks) bytes)"
else
  echo "• ANDROID_KEYSTORE_BASE64 not in .env — skipping signing (release will debug-sign)."
fi

echo "Done. Secrets are git-ignored; never commit them."
